#!groovy

// Generated by IBM TransformationAdvisor
// Thu Jan 24 09:02:36 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'sample'
    mvnCommands = '--version'
    test='false'
}